version: "2"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
    image: docker-app
    ports:
      - "4000:4000"
    links:
      - postgres
    environment:
      - PGUSER=musi
      - PGPASSWORD=secret
      - PGDATABASE=musilist

  postgres:
    container_name: postgres
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=musi
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=musilist
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: {}